# Generated by Django 2.1.1 on 2018-11-18 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.FileField(upload_to='')),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentid', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('image', models.FileField(upload_to='')),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=13)),
                ('profile', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='FeatureLookup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('categoryid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.Category')),
            ],
        ),
        migrations.CreateModel(
            name='FeatureValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=40)),
                ('featureid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.FeatureLookup')),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('password', models.SlugField(max_length=30)),
                ('isactive', models.BooleanField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('orderid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('brandid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.Brand')),
                ('categoryid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.Category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
                ('productid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('orderid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.Order')),
            ],
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('hno', models.CharField(max_length=20)),
                ('area', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('pin', models.IntegerField()),
                ('landmark', models.CharField(max_length=100)),
                ('loginid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.Login')),
            ],
        ),
        migrations.AddField(
            model_name='orderitem',
            name='productid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.Product'),
        ),
        migrations.AddField(
            model_name='order',
            name='addressid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.ShippingAddress'),
        ),
        migrations.AddField(
            model_name='order',
            name='loginid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.Login'),
        ),
        migrations.AddField(
            model_name='featurevalue',
            name='productid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.Product'),
        ),
        migrations.AddField(
            model_name='customer',
            name='loginid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.Login'),
        ),
        migrations.AddField(
            model_name='cart',
            name='loginid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.Login'),
        ),
        migrations.AddField(
            model_name='cart',
            name='productid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.Product'),
        ),
    ]
