# Generated by Django 2.1.1 on 2018-12-19 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0004_remove_customer_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xtoken', models.CharField(max_length=32)),
                ('datetime', models.DateTimeField()),
                ('loginid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.Login')),
            ],
        ),
    ]
